# Generated by Django 3.0.2 on 2020-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_saldo', models.CharField(default="[{'0':'0', '1':'0', '2':'0', '3':'0'}]", max_length=50)),
                ('udgift_oprettet', models.CharField(default="[{'0':'0', '1':'0', '2':'0', '3':'0'}]", max_length=50)),
                ('tankning_oprettet', models.CharField(default="[{'0':'0', '1':'0', '2':'0', '3':'0'}]", max_length=50)),
            ],
        ),
    ]
