# Generated by Django 3.0.2 on 2020-03-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_is_vip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='is_VIP',
        ),
    ]
