# Generated by Django 3.0.2 on 2020-01-28 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tankning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField(default=datetime.date.today)),
                ('pris', models.FloatField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
