# Generated by Django 3.0.2 on 2020-02-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transactionid'),
        ('tbu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankning',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId'),
            preserve_default=False,
        ),
    ]
