# Generated by Django 3.0.2 on 2020-01-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankning',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
