# Generated by Django 3.0.2 on 2020-01-28 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbu', '0002_auto_20200128_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betaling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField(default=datetime.date.today)),
                ('amount', models.FloatField()),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
