# Generated by Django 3.0.2 on 2020-04-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbu', '0002_betaling_is_indskud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betaling',
            name='is_indskud',
        ),
    ]
