# Generated by Django 3.0.2 on 2020-01-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbu', '0003_betaling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tankning',
            old_name='pris',
            new_name='amount',
        ),
    ]
