# Generated by Django 3.0.2 on 2020-01-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbu', '0004_auto_20200129_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betaling',
            old_name='dato',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tankning',
            old_name='dato',
            new_name='date',
        ),
    ]
