# Generated by Django 3.0.2 on 2020-04-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbu', '0006_auto_20200419_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betaling',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
