# Generated by Django 3.0.2 on 2020-01-27 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ture',
            name='dato',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
