# Generated by Django 3.0.2 on 2020-01-27 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0002_ture_dato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ture',
            old_name='km',
            new_name='km_count',
        ),
        migrations.AlterField(
            model_name='ture',
            name='dato',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
