# Generated by Django 3.0.2 on 2020-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0003_auto_20200127_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ture',
            name='km_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ture',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
