# Generated by Django 3.0.2 on 2020-01-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0004_auto_20200127_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ture',
            name='km_count',
            field=models.IntegerField(default=123456),
        ),
    ]
