# Generated by Django 3.0.2 on 2020-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0006_auto_20200128_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ture',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
