# Generated by Django 3.0.2 on 2020-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0007_auto_20200128_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ture',
            name='extra_pas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
