# Generated by Django 3.0.2 on 2020-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0008_ture_extra_pas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ture',
            name='km_count',
            field=models.IntegerField(),
        ),
    ]
