# Generated by Django 3.0.2 on 2020-01-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kasper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('saldo', models.FloatField()),
                ('km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kirsten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('saldo', models.FloatField()),
                ('km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('saldo', models.FloatField()),
                ('km', models.IntegerField()),
            ],
        ),
    ]
