# Generated by Django 3.0.2 on 2020-03-02 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KmPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=2.0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionId',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=100)),
                ('user', models.CharField(default='AnonymousUser', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo', models.FloatField()),
                ('amount', models.FloatField(default=0.0)),
                ('km', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId')),
            ],
        ),
        migrations.CreateModel(
            name='Kirsten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo', models.FloatField()),
                ('amount', models.FloatField(default=0.0)),
                ('km', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId')),
            ],
        ),
        migrations.CreateModel(
            name='Kasper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo', models.FloatField()),
                ('amount', models.FloatField(default=0.0)),
                ('km', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId')),
            ],
        ),
        migrations.CreateModel(
            name='FarMor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo', models.FloatField()),
                ('amount', models.FloatField(default=0.0)),
                ('km', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId')),
            ],
        ),
    ]
