# Generated by Django 3.0.2 on 2020-03-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmor',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmor',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='kasper',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kasper',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='kirsten',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kirsten',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='marie',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marie',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
    ]
