# Generated by Django 3.0.2 on 2020-01-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200130_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarMor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('saldo', models.FloatField()),
                ('km', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
