# Generated by Django 3.0.2 on 2020-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionId',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
    ]
