# Generated by Django 3.0.2 on 2020-03-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200302_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(default=0.0)),
            ],
        ),
    ]
