# Generated by Django 3.0.2 on 2020-02-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmor',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kasper',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirsten',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marie',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId'),
            preserve_default=False,
        ),
    ]
