# Generated by Django 3.0.2 on 2020-02-15 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200202_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmor',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kasper',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kirsten',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marie',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transactionid',
            name='user',
            field=models.CharField(default='Ukendt', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionid',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
