# Generated by Django 3.0.2 on 2020-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200310_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onbankaccount',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
