# Generated by Django 3.0.2 on 2020-03-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200311_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onbankaccount',
            name='description',
        ),
        migrations.AddField(
            model_name='onbankaccount',
            name='user',
            field=models.CharField(default='AnonymousUser', max_length=20),
        ),
    ]
