# Generated by Django 3.0.2 on 2020-03-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_onbankaccount_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kmprice',
            options={'verbose_name': 'Edited Address'},
        ),
    ]
