# Generated by Django 3.0.2 on 2020-03-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200328_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kmprice',
            options={'verbose_name': 'Km Price'},
        ),
    ]
