# Generated by Django 3.0.2 on 2020-03-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200328_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmor',
            options={'verbose_name_plural': '3. Farmor & Farfar'},
        ),
        migrations.AlterModelOptions(
            name='kasper',
            options={'verbose_name_plural': '2. Kasper'},
        ),
        migrations.AlterModelOptions(
            name='kirsten',
            options={'verbose_name_plural': '4. Kirsten'},
        ),
        migrations.AlterModelOptions(
            name='kmprice',
            options={'verbose_name_plural': 'Km-Price'},
        ),
        migrations.AlterModelOptions(
            name='marie',
            options={'verbose_name_plural': '1. Marie'},
        ),
        migrations.AlterModelOptions(
            name='onbankaccount',
            options={'verbose_name_plural': 'Bank account'},
        ),
    ]
