# Generated by Django 3.0.2 on 2020-03-28 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200328_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('km', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TransactionId')),
            ],
            options={
                'verbose_name_plural': 'Guest',
            },
        ),
    ]
