# Generated by Django 3.0.2 on 2020-04-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name_plural': '5. Guest'},
        ),
    ]
