# Generated by Django 3.0.2 on 2020-04-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200403_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Gabriel',
        ),
        migrations.AlterModelOptions(
            name='gabriel',
            options={'verbose_name_plural': '5. Gabriel'},
        ),
    ]
