# Generated by Django 3.0.2 on 2020-01-29 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('km_count', models.IntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('extra_pas', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
