# Generated by Django 3.0.2 on 2020-01-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ture',
            name='delta_km',
            field=models.IntegerField(default=0),
        ),
    ]
