# Generated by Django 3.0.2 on 2020-01-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ture', '0003_auto_20200130_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='ture',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
