# Generated by Django 3.0.2 on 2020-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0002_userpreferences_tur_oprettet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_que', models.CharField(default='[]', max_length=5000)),
            ],
        ),
    ]
