# Generated by Django 3.0.2 on 2020-04-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailing', '0003_emailque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='monthly_saldo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tankning_oprettet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tur_oprettet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='udgift_oprettet',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_saldo', models.BooleanField(default=True)),
                ('udgift_oprettet', models.BooleanField(default=False)),
                ('tankning_oprettet', models.BooleanField(default=False)),
                ('tur_oprettet', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
