# Generated by Django 3.0.2 on 2020-04-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0004_auto_20200403_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
