# Generated by Django 3.0.2 on 2020-04-03 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('emailing', '0006_delete_emailpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_saldo', models.BooleanField(default=True)),
                ('udgift_oprettet', models.BooleanField(default=False)),
                ('tankning_oprettet', models.BooleanField(default=False)),
                ('tur_oprettet', models.BooleanField(default=False)),
            ],
        ),
    ]
