# Generated by Django 3.0.2 on 2020-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0007_emailpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpreferences',
            name='indbetaling_oprettet',
            field=models.BooleanField(default=False),
        ),
    ]
